//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPrompt.Update {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevPrompt.Update.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start: {0}.
        /// </summary>
        public static string Error_FailedToStart {
            get {
                return ResourceManager.GetString("Error.FailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Closing DevPrompt windows.
        /// </summary>
        public static string Stage_Closing_Text {
            get {
                return ResourceManager.GetString("Stage.Closing.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Done.
        /// </summary>
        public static string Stage_Done_Text {
            get {
                return ResourceManager.GetString("Stage.Done.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Downloading files.
        /// </summary>
        public static string Stage_Downloading_Text {
            get {
                return ResourceManager.GetString("Stage.Downloading.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Copying files.
        /// </summary>
        public static string Stage_Installing_Text {
            get {
                return ResourceManager.GetString("Stage.Installing.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Window_Cancel {
            get {
                return ResourceManager.GetString("Window.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update failed..
        /// </summary>
        public static string Window_FailureIntro {
            get {
                return ResourceManager.GetString("Window.FailureIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update DevPrompt.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://peterspada.com/Download/DevPrompt?type=zip.
        /// </summary>
        public static string ZipFileUrl {
            get {
                return ResourceManager.GetString("ZipFileUrl", resourceCulture);
            }
        }
    }
}
