//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPrompt.ProcessWorkspace {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevPrompt.ProcessWorkspace.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clone.
        /// </summary>
        public static string Command_Clone {
            get {
                return ResourceManager.GetString("Command.Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_lose.
        /// </summary>
        public static string Command_Close {
            get {
                return ResourceManager.GetString("Command.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All But This.
        /// </summary>
        public static string Command_CloseAllButThis {
            get {
                return ResourceManager.GetString("Command.CloseAllButThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console _Defaults.
        /// </summary>
        public static string Command_ConsoleDefaults {
            get {
                return ResourceManager.GetString("Command.ConsoleDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console _Properties.
        /// </summary>
        public static string Command_ConsoleProperties {
            get {
                return ResourceManager.GetString("Command.ConsoleProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_etach.
        /// </summary>
        public static string Command_Detach {
            get {
                return ResourceManager.GetString("Command.Detach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Set tab name....
        /// </summary>
        public static string Command_SetTabName {
            get {
                return ResourceManager.GetString("Command.SetTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Prompts.
        /// </summary>
        public static string ProcessWorkspace_Name {
            get {
                return ResourceManager.GetString("ProcessWorkspace.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Tab Name.
        /// </summary>
        public static string SetTabName_Title {
            get {
                return ResourceManager.GetString("SetTabName.Title", resourceCulture);
            }
        }
    }
}
