import "oaidl.idl";
import "ocidl.idl";

interface IAppHost;
interface IApp;
interface IProcessHost;
interface IProcess;
interface IVisualStudioInstance;
interface IVisualStudioInstances;

// MUST match IAppHost.cs
[object, uuid("42d16e5c-8acf-4dcb-882d-b41974190e53")]
interface IAppHost : IUnknown
{
    HRESULT CanGrab(const wchar_t* exePath, VARIANT_BOOL automatic, [out, retval] int* value);

    // Processes
    HRESULT OnProcessOpening(IProcess* process, VARIANT_BOOL activate, const wchar_t* path);
    HRESULT OnProcessClosing(IProcess* process);
    HRESULT OnProcessEnvChanged(IProcess* process, const wchar_t* env);
    HRESULT OnProcessTitleChanged(IProcess* process, const wchar_t* title);
};

[object, uuid("151c2791-131f-43b6-9384-0f5a8c1c9461")]
interface IApp : IUnknown
{
    HRESULT Dispose();
    HRESULT Activate();
    HRESULT Deactivate();
    HRESULT GetGrabProcesses(BSTR* processes);
    HRESULT GrabProcess(int id);
    HRESULT CreateProcessHostWindow(HWND parentHwnd, [out, retval] IProcessHost** obj);
    HRESULT MainWindowProc(HWND hwnd, int msg, WPARAM wp, LPARAM lp);
};

[object, uuid("cedddf4b-b229-4a17-8b10-140e53464efd")]
interface IProcessHost : IUnknown
{
    HRESULT Dispose();
    HRESULT Activate();
    HRESULT Deactivate();
    HRESULT Show();
    HRESULT Hide();
    HRESULT Focus();
    HRESULT GetWindow([out, retval] HWND* hwnd);

    HRESULT RunProcess(
        const wchar_t* executable,
        const wchar_t* arguments,
        const wchar_t* startingDirectory,
        [out, retval] IProcess** obj);

    HRESULT RestoreProcess(const wchar_t* state, [out, retval] IProcess** obj);
    HRESULT CloneProcess(IProcess* process, [out, retval] IProcess** obj);
    HRESULT ContainsProcess(IProcess* process, [out, retval] VARIANT_BOOL* value);
};

[object, uuid("e3b1d8b5-bce5-4522-ad92-44ce6edda69c")]
interface IProcess : IUnknown
{
    HRESULT Dispose();
    HRESULT Detach();
    HRESULT Activate();
    HRESULT Deactivate();
    HRESULT GetWindow([out, retval] HWND* hwnd);
    HRESULT GetState([out, retval] BSTR* value);
    HRESULT Focus();
    HRESULT SystemCommandDefaults();
    HRESULT SystemCommandProperties();
};

[object, uuid("4c1047a1-e701-4024-aeed-08a38c70584e")]
interface IVisualStudioInstance : IUnknown
{
    HRESULT GetInstallationName([out, retval] BSTR* value);
    HRESULT GetInstanceId([out, retval] BSTR* value);
    HRESULT GetInstallationPath([out, retval] BSTR* value);
    HRESULT GetProductPath([out, retval] BSTR* value);
    HRESULT GetInstallationVersion([out, retval] BSTR* value);
    HRESULT GetChannelId([out, retval] BSTR* value);
};

[object, uuid("8a4b9d86-da6e-4d15-9ee0-58080da25282")]
interface IVisualStudioInstances : IUnknown
{
    HRESULT GetCount([out, retval] int* count);
    HRESULT GetValue(int index, [out, retval] IVisualStudioInstance** value);
};
